### ISSUE TITLE
 3 "unexpected error has occured" dialogs with logs related to NvThermalSensors after every wake from sleep

### ISSUE THREAD

**Issue by knowsshit** [TimSirmovics/FanControl.NvThermalSensors#1]
See https://github.com/Rem0o/FanControl.Releases/issues/2292 where Rem0o points out a null reference in GetThermalSensors

Every time after Windows wakes from sleep, FanControl pops up and I have to dismiss three identical error dialogs with "An unexpected error has occured and has been added to the log file."

The GPU og GPU Hot Spot sensors seems to work fine, so I just want the errors supressed so I don't have to have FanControl popping up and making me dismiss the three error dialog boxes, but I guess the NvThermalSensors needs to be fixed for the null reference so an error is not thrown.

Setup:
Asus ROG Z790 HERO, i9-13900k, Asus ROG STRIX 4090, Windows 11, latest updates and drivers.

Errors from the log.txt file:
[log.txt](https://github.com/TimSirmovics/FanControl.NvThermalSensors/files/14158618/log.txt)

**Comment by TimSirmovics** [comment]
Sorry I did not realise this issue was opened, I'll check this out.
Are you still experiencing the same issue?

**Comment by knowsshit** [comment]
Yes, I am. Tell me if you need any more information.

**Comment by vfib** [comment]
Hello,
Im expierencing the same error. log.txt is appended.
Best regards
[log.txt](https://github.com/TimSirmovics/FanControl.NvThermalSensors/files/15232595/log.txt)

**Comment by TimSirmovics** [comment]
Please try the latest release.

**Comment by vfib** [comment]
> Please try the latest release.

Seems to have fixed it. Thanks for your quick response

**Comment by knowsshit** [comment]
> Please try the latest release.

Can confirm! I can now resume from sleep and there are no error dialogs in FanControl! Thank you very much!

Now I no longer have to dread opening FanControl and click away 3 dialog boxes multiplied by the amount of times Windows has slept since I last rebooted or dismissed them manually.
